# Generated by Django 5.0.2 on 2024-05-02 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_customercredential_total_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
