# Generated by Django 5.0.2 on 2024-05-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_customerdetails_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercredential',
            name='total_exp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customercredential',
            name='total_inc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
