# Generated by Django 5.0.2 on 2024-05-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_alter_customercredential_total_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
