# Generated by Django 5.0.2 on 2024-05-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_alter_customercredential_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercredential',
            name='remaining',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
